### ISSUE TITLE
Normal behaviour on starting?

### ISSUE THREAD

**Issue by dimentorium** [sergey-tihon/Stanford.NLP.NET#58] opened 2017-03-03 09:18 UTC
HI Sergey,
currently starting to work with Stanford NLP for .NET from you. I just wanted to check if its normal, when I start the demo application for coreNLP, I get an error in the console on issue with an slf4j package, and after this VS shows lots of java util exceptions, that a method is not found.
And after around 20 seconds, the results for the analysis are shown. But it takes every time these 20 seconds before it runs. Is that expected?
I am using the 3.7 build with the english model files

Thanks Phil

**Comment by sergey-tihon** [comment] 2017-03-05 17:56
Some warning log messages are expected.
20 sec startup time is not (at least it depend what you do and what model you use)
[Couple seconds loading time](https://github.com/sergey-tihon/Stanford.NLP.NET/issues/40) is OK, but not 20.

**Comment by dimentorium** [comment] 2017-03-10 14:25
Thanks for the info, what I get is in the console:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

And then in the event log in VS lots of:
Exception: Exception at: 'java.lang.NoSuchMethodException' in IKVM.OpenJDK.Core.dll ("java.util.Hashtable.readResolve()"). Ausnahme ausgelöst: 'java.lang.NoSuchMethodException' in IKVM.OpenJDK.Core.dll ("java.util.Hashtable.readResolve()")	1,58 Sek.		[9976] <Kein Name> 

And
Exception: Exception at: 'LookaheadSuccess' in stanford-corenlp-3.7.0.dll (""). Ausnahme ausgelöst: 'LookaheadSuccess' in stanford-corenlp-3.7.0.dll ("")	21,64 Sek.		[9976] <Kein Name> 

Any idea if I am making something wrong?

**Comment by andreimanu** [comment] 2017-04-22 12:13
I'm getting the same error messages, and I have been for a while.
It does take a while to load, depending on your specs (keep in mind, that, depending on what you plan on using, it might have to load up to 900 MB in RAM)
The exceptions make the load time slower thanks to the way VS handles them, but after they are all thrown and caught, it works as intended.

**Comment by dimentorium** [comment] 2017-04-24 06:51
HI andreimanu,
thanks for the info! So everything is good to go.

**Comment by sergey-tihon** [comment] 2017-05-02 04:03
I close this issue in favor of #65 
I've fixed some loading errors in v3.7.0.1

**Closed by sergey-tihon** 2017-05-02 04:03 UTC
